### ISSUE TITLE
dockerに入ってもtscができない

### ISSUE THREAD

**Issue by keek420** [teamdevD/teamdevD-devlog#25]
##Bug report

### 概要
main ブランチからpullしたdockerでtscが認識されていない

### 再現手順
1. mainブランチをpull
2. docker compose up -d
3. docker container exec -it docker-ubuntu-1  bash
4. tsc　-v

no such commnd表示

### 期待する動作
4のtsc が通る

**Comment by SekkyDSL** [comment]
@keek420 
グローバルでなく作業用リポジトリに導入しているので問題ありません。

**Comment by SekkyDSL** [comment]
自動作成したmy-projectディレクトリ内では作業できます。
